[[redirects]]
  from = "/admin"
  to = "https://adminadlpartnership.sawirstudio.com/wp-admin"
  status = 301

  [[redirects]]
  from = "/wp-json"
  to = "https://adminadlpartnership.sawirstudio.com/wp-json"
  status = 301

  # [[redirects]]
  # from = "https://adlpartnership.com"
  # to = "/coming-soon"
  # status = 302

  # [[redirects]]
  # from = "https://www.adlpartnership.com"
  # to = "/coming-soon"
  # status = 302

[[redirects]]
  from = "https://adlpartnership.sawirstudio.com"
  to = "/"
  status = 301

   [[redirects]]
  from = "https://adlpartnership.netlify.com/*"
  to = "https://www.adlpartnership.com/:splat"
  status = 301

  

  [[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"